#!/usr/bin/env python3
"""Merge the per-batch title-research results into 1-SOURCES/liturgy-titles.json.

    python3 4-SYSTEM/scripts/build_title_registry.py <research-dir>

<research-dir> holds batchNN.in.json / batchNN.out.json pairs produced by the
title-research pass: for each of the 95 texts, the established English and
Chinese title of the work where one exists, and a flag saying whether the title
is *attested* (found in a published translation or reference work, with the URL)
or *translated* (rendered by us because no established title was found).

The registry is the join point between three things that are otherwise only
connected by a Tibetan filename: the source note, the backend ids the text was
uploaded under, and the titles the translation tracks display.
"""

import datetime
import json
import os
import re
import sys

VAULT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC_DIR = os.path.join(VAULT, "1-SOURCES", "Text")
LEDGER = os.path.join(VAULT, "4-SYSTEM", "scripts", "upload_ledger.json")
CATALOG = os.path.join(VAULT, "1-SOURCES", "liturgy-catalog.json")
OUT = os.path.join(VAULT, "1-SOURCES", "liturgy-titles.json")

FIELDS = ("en_title", "en_attested", "en_source", "en_alt",
          "zh_title", "zh_attested", "zh_source", "zh_alt",
          "confidence", "notes")


def clean_title(value):
    """Titles arrive from research as prose; keep them as plain single-line text."""
    if not isinstance(value, str):
        return ""
    v = value.strip().strip('"').strip("'").strip()
    v = re.sub(r"\s+", " ", v)
    v = re.sub(r"^[#>*\s]+", "", v)
    return v.rstrip("།༎༏༑ ").strip()


NOTE = os.path.join(VAULT, "1-SOURCES", "Titles to review.md")


def write_review_note(texts):
    """A reading copy of the registry, ordered so the titles that need a human
    eye come first. Only the unattested ones are actually a decision."""
    def rows(items, lang):
        out = []
        for t in items:
            src = t[f"{lang}_source"]
            title = t[f"{lang}_title"] or "—"
            link = f"[source]({src})" if src else ""
            alt = ", ".join(t[f"{lang}_alt"][:2])
            out.append(f"| {t['bo_title']} | {title} | {link} | {alt} |")
        return out

    lines = [
        "---",
        "title: Titles to review",
        "file_type: worklist",
        "---",
        "",
        "# Titles to review",
        "",
        "English and Chinese titles for the 95 liturgy texts. Generated by",
        "`4-SYSTEM/scripts/build_title_registry.py`; the machine-readable form is",
        "`liturgy-titles.json`, which is what the stamping script reads.",
        "",
        "**Attested** means the title was found in a published translation or",
        "reference work, and the source column links to where. **Ours** means no",
        "established title was found and the title was translated for this vault —",
        "those are the ones worth a human eye. An unattested title is not a guess",
        "about the text's identity; every text was confirmed against its own",
        "opening lines first.",
        "",
    ]
    for lang, label in (("en", "English"), ("zh", "Chinese")):
        ours = [t for t in texts if not t[f"{lang}_attested"]]
        att = [t for t in texts if t[f"{lang}_attested"]]
        lines += [
            f"## {label} — ours, needs review ({len(ours)})",
            "",
            "| Tibetan | Title | Source | Alternatives |",
            "| --- | --- | --- | --- |",
            *rows(ours, lang),
            "",
            f"## {label} — attested ({len(att)})",
            "",
            "| Tibetan | Title | Source | Alternatives |",
            "| --- | --- | --- | --- |",
            *rows(att, lang),
            "",
        ]
    with open(NOTE, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {NOTE}")


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    rdir = sys.argv[1]

    ledger = json.load(open(LEDGER))
    catalog = {t["file"][:-3]: t for t in json.load(open(CATALOG))["texts"]}

    # source-of-truth Tibetan titles, straight off the notes
    bo = {}
    for name in sorted(os.listdir(SRC_DIR)):
        if not name.endswith(".md"):
            continue
        stem = name[:-3]
        text = open(os.path.join(SRC_DIR, name)).read()
        t = re.search(r"^title:\s*(.+?)\s*$", text, re.M)
        h = re.search(r"^# (.+?)\s*\^0\s*$", text, re.M)
        bo[stem] = (t.group(1).strip() if t else stem,
                    h.group(1).strip() if h else "")

    researched, dupes = {}, []
    for name in sorted(os.listdir(rdir)):
        if not re.match(r"batch\d+\.out\.json$", name):
            continue
        for rec in json.load(open(os.path.join(rdir, name))):
            stem = rec.get("stem", "")
            if stem in researched:
                dupes.append(stem)
            researched[stem] = rec

    texts, missing, unattested = [], [], []
    for stem in sorted(bo):
        r = researched.get(stem)
        if not r:
            missing.append(stem)
            r = {}
        row = {
            "stem": stem,
            "rank": catalog.get(stem, {}).get("rank"),
            "bo_title": bo[stem][0],
            "bo_heading": bo[stem][1],
            "text_id": ledger.get(stem, {}).get("text_id", ""),
            "edition_id": ledger.get(stem, {}).get("edition_id", ""),
        }
        for f in FIELDS:
            v = r.get(f, [] if f.endswith("_alt") else ("" if not f.endswith("_attested") else False))
            if f.endswith("_title"):
                v = clean_title(v)
            elif f.endswith("_alt"):
                v = [clean_title(x) for x in v if clean_title(x)]
            elif f.endswith("_attested"):
                v = bool(v)
            row[f] = v
        # a title we invented is never "attested", whatever the researcher said
        for lang in ("en", "zh"):
            if not row[f"{lang}_source"]:
                row[f"{lang}_attested"] = False
            if row[f"{lang}_title"] and not row[f"{lang}_attested"]:
                unattested.append((stem, lang))
        texts.append(row)

    payload = {
        "generated": datetime.date.today().isoformat(),
        "what": "Established English and Chinese titles for the 95 liturgy texts, "
                "with the backend ids each text was uploaded under.",
        "attested": "true = the title is used in a published translation or reference "
                    "work, and `*_source` is where it was found. false = no established "
                    "title was found and this one was translated for this vault; "
                    "review before treating it as canonical.",
        "count": len(texts),
        "texts": texts,
    }
    with open(OUT, "w") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write("\n")

    write_review_note(texts)

    n_en = sum(1 for t in texts if t["en_attested"])
    n_zh = sum(1 for t in texts if t["zh_attested"])
    n_en_any = sum(1 for t in texts if t["en_title"])
    n_zh_any = sum(1 for t in texts if t["zh_title"])
    print(f"wrote {OUT}")
    print(f"  {len(texts)} texts")
    print(f"  english: {n_en_any} titles, {n_en} attested / {n_en_any - n_en} translated by us")
    print(f"  chinese: {n_zh_any} titles, {n_zh} attested / {n_zh_any - n_zh} translated by us")
    if missing:
        print(f"  !! {len(missing)} texts had no research record:", file=sys.stderr)
        for s in missing:
            print(f"       {s}", file=sys.stderr)
    if dupes:
        print(f"  !! duplicate research records: {dupes}", file=sys.stderr)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
